jobs:
  build:
  
    docker: # run the steps with Docker
    - image: circleci/openjdk:8-jdk-stretch
    
    steps:
      - checkout

      - run: 
          command: mvn package
          working_directory: web-app
          
      - store_artifacts:
          path: web-app/target/web-app.war
